import { describe, expect, it } from 'vitest'; import { gameReducer, initialState, selectPayment } from './reducer'; import { animalCount, buildDeck, hasCards, ownsQuartet, scorePlayer, totalMoney } from './rules'; import type { GameState, Player } from './types';
const start=()=>gameReducer(initialState,{type:'START',names:['Ada','Bea'],seed:1});
describe('Kuhhandel rules',()=>{
 it('validates bidding and advances the high bid',()=>{let s=gameReducer(start(),{type:'DRAW_AUCTION'});s=gameReducer(s,{type:'BID',playerId:'p2',amount:50});expect(s.auction?.highestBid).toBe(50);expect(()=>gameReducer(s,{type:'BID',playerId:'p2',amount:20})).toThrow('Illegal bid');expect(()=>gameReducer(s,{type:'BID',playerId:'p1',amount:100})).toThrow('Illegal bid')});
 it('exchanges auction payment and transfers the animal',()=>{let s=gameReducer(start(),{type:'DRAW_AUCTION'});const card=s.auction!.card,before=totalMoney(s.players[0].money);s=gameReducer(s,{type:'BID',playerId:'p2',amount:50});s=gameReducer(s,{type:'RESOLVE_AUCTION'});expect(s.players[1].animals).toContainEqual(card);expect(totalMoney(s.players[0].money)).toBeGreaterThan(before)});
 it('selects enough payment cards',()=>expect(totalMoney(selectPayment([10,20,50],55))).toBeGreaterThanOrEqual(55));
 it('treats zero cards as valid bluff offers',()=>expect(hasCards([0,0,50],[0,0])).toBe(true));
 it('detects quartet ownership and scoring',()=>{const cards=buildDeck().filter(c=>c.animal==='cow');const p:Player={id:'p',name:'P',money:[],animals:cards};expect(animalCount(p,'cow')).toBe(4);expect(ownsQuartet(p,'cow')).toBe(true);expect(scorePlayer(p)).toBe(800)});
 it('rejects a trade without shared animals',()=>expect(()=>gameReducer(start(),{type:'START_TRADE',opponentId:'p2',animal:'cow',offer:[0]})).toThrow('Illegal trade'));
 it('finishes after the final auction resolves',()=>{let s=start();s={...s,deck:s.deck.slice(0,1)};s=gameReducer(s,{type:'DRAW_AUCTION'});s=gameReducer(s,{type:'RESOLVE_AUCTION'});expect(s.phase).toBe('finished');expect(s.winnerIds.length).toBeGreaterThan(0)});
 it('resolves a bluff-versus-money direct trade deterministically',()=>{const deck=buildDeck(),cow=deck.filter(c=>c.animal==='cow');let s=start();s={...s,players:[{...s.players[0],animals:[cow[0]]},{...s.players[1],animals:cow.slice(1,2)}]} as GameState;s=gameReducer(s,{type:'START_TRADE',opponentId:'p2',animal:'cow',offer:[0]});s=gameReducer(s,{type:'RESPOND_TRADE',response:[50]});s=gameReducer(s,{type:'RESOLVE_TRADE',choice:'counter'});expect(s.players[0].animals).toHaveLength(2);expect(s.players[1].animals).toHaveLength(0)});
});
