import type { GameAction, GameState, Money, Player } from './types';
import { STARTING_MONEY, buildDeck, hasCards, isGameOver, removeCards, scorePlayer, shuffled, totalMoney, winnerIds } from './rules';
export const initialState:GameState={version:1,players:[],deck:[],currentPlayer:0,phase:'setup',history:[],winnerIds:[],turn:1};
const log=(s:GameState,text:string,tone:'auction'|'trade'|'turn'='turn')=>[{id:`${s.turn}-${s.history.length}-${text}`,text,tone},...s.history].slice(0,40);
const update=(ps:Player[],id:string,fn:(p:Player)=>Player)=>ps.map(p=>p.id===id?fn(p):p);
const validMoney=(cards:number[]):cards is Money[]=>cards.every(c=>[0,10,20,50,100,200,500].includes(c));
export function gameReducer(state:GameState,action:GameAction):GameState{switch(action.type){
case 'RESTORE': return action.state;
case 'START':{if(action.names.length<2||action.names.length>5)throw Error('Kuhhandel needs 2–5 players');const players=action.names.map((name,i)=>({id:`p${i+1}`,name:name.trim()||`Player ${i+1}`,money:[...STARTING_MONEY],animals:[]}));return{...initialState,players,deck:shuffled(buildDeck(),action.seed),phase:'choose',history:[{id:'start',text:'The livestock market is open.',tone:'turn'}]};}
case 'DRAW_AUCTION':{if(state.phase!=='choose'||!state.deck.length)throw Error('No auction may start');const[card,...deck]=state.deck;return{...state,deck,phase:'auction',auction:{card,bids:{},highestBid:0},history:log(state,`${state.players[state.currentPlayer].name} versteigert ${card.animal}.`,'auction')};}
case 'BID':{if(!state.auction||state.phase!=='auction')throw Error('No active auction');const bidder=state.players.find(p=>p.id===action.playerId);if(!bidder||action.playerId===state.players[state.currentPlayer].id||action.amount<=state.auction.highestBid||totalMoney(bidder.money)<action.amount)throw Error('Illegal bid');return{...state,auction:{...state.auction,highestBid:action.amount,highestBidder:action.playerId,bids:{...state.auction.bids,[action.playerId]:action.amount}},history:log(state,`${bidder.name} bids ${action.amount}.`,'auction')};}
case 'RESOLVE_AUCTION':{if(!state.auction)throw Error('No active auction');const seller=state.players[state.currentPlayer],{card,highestBid,highestBidder}=state.auction;let players=state.players,text=`${seller.name} keeps ${card.animal}.`;if(highestBidder){const buyer=players.find(p=>p.id===highestBidder)!;const payment=selectPayment(buyer.money,highestBid);players=update(players,buyer.id,p=>({...p,money:removeCards(p.money,payment),animals:[...p.animals,card]}));players=update(players,seller.id,p=>({...p,money:[...p.money,...payment]}));text=`${buyer.name} wins ${card.animal} for ${highestBid}.`;}else players=update(players,seller.id,p=>({...p,animals:[...p.animals,card]}));return finish({...state,players,auction:undefined,phase:'choose',history:log(state,text,'auction')});}
case 'START_TRADE':{const actor=state.players[state.currentPlayer],opponent=state.players.find(p=>p.id===action.opponentId);if(state.phase!=='choose'||!opponent||!validMoney(action.offer)||!hasCards(actor.money,action.offer)||!actor.animals.some(a=>a.animal===action.animal)||!opponent.animals.some(a=>a.animal===action.animal))throw Error('Illegal trade');return{...state,phase:'trade',trade:{initiator:actor.id,opponent:opponent.id,animal:action.animal,offer:action.offer},history:log(state,`${actor.name} challenges ${opponent.name} to a trade.`,'trade')};}
case 'RESPOND_TRADE':{if(!state.trade||!validMoney(action.response))throw Error('No active trade');const opponent=state.players.find(p=>p.id===state.trade!.opponent)!;if(!hasCards(opponent.money,action.response))throw Error('Illegal response');return{...state,trade:{...state.trade,response:action.response}};}
case 'RESOLVE_TRADE':{const t=state.trade;if(!t||!t.response)throw Error('Trade is not ready');const initiator=state.players.find(p=>p.id===t.initiator)!,opponent=state.players.find(p=>p.id===t.opponent)!;const giver=action.choice==='accept'?initiator:opponent,taker=action.choice==='accept'?opponent:initiator,payment=action.choice==='accept'?t.offer:t.response,animals=giver.animals.filter(a=>a.animal===t.animal);let players=update(state.players,giver.id,p=>({...p,money:[...p.money,...payment],animals:p.animals.filter(a=>a.animal!==t.animal)}));players=update(players,taker.id,p=>({...p,money:removeCards(p.money,payment),animals:[...p.animals,...animals]}));return finish({...state,players,trade:undefined,phase:'choose',history:log(state,`${taker.name} wins the trade (${totalMoney(payment)}).`,'trade')});}
case 'END_TURN':{if(state.phase!=='choose')throw Error('Finish the current action first');const currentPlayer=(state.currentPlayer+1)%state.players.length;return{...state,currentPlayer,turn:state.turn+1,history:log(state,`${state.players[currentPlayer].name}'s turn.`)};}}}
export function selectPayment(hand:Money[],amount:number):Money[]{const positive=[...hand].filter(v=>v>0).sort((a,b)=>b-a),selected:Money[]=[];let sum=0;for(const card of positive){if(sum>=amount)break;selected.push(card);sum+=card;}if(sum<amount)throw Error('Insufficient funds');return selected;}
function finish(s:GameState):GameState{if(!isGameOver(s))return s;return{...s,phase:'finished',winnerIds:winnerIds(s.players),history:log(s,`Game over. Highest score: ${Math.max(...s.players.map(scorePlayer))}.`) };}
